{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.ingester.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: {{ include "common.capabilities.networkPolicy.apiVersion" . }}
metadata:
  name: {{ template "grafana-tempo.ingester.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: ingester
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.ingester.podLabels .Values.commonLabels ) "context" . ) }}
  podSelector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: ingester
  policyTypes:
    - Ingress
    - Egress
  {{- if .Values.ingester.networkPolicy.allowExternalEgress }}
  egress:
    - {}
  {{- else }}
  egress:
    # Allow dns resolution
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    # Allow outbound connections to tempo cluster
    - ports:
        - port: {{ .Values.tempo.containerPorts.web }}
        - port: {{ .Values.tempo.containerPorts.gossipRing }}
        - port: {{ .Values.tempo.containerPorts.grpc }}
        {{- if .Values.tempo.traces.jaeger.thriftCompact.enabled }}
        - port: {{ .Values.tempo.traces.jaeger.thriftCompact.port }}
          protocol: UDP
        {{- end }}
        {{- if .Values.tempo.traces.jaeger.thriftBinary.enabled }}
        - port: {{ .Values.tempo.traces.jaeger.thriftBinary.port }}
          protocol: UDP
        {{- end }}
        {{- if .Values.tempo.traces.jaeger.thriftHttp.enabled }}
        - port: {{ .Values.tempo.traces.jaeger.thriftHttp.port }}
        {{- end }}
        {{- if .Values.tempo.traces.jaeger.grpc.enabled }}
        - port: {{ .Values.tempo.traces.jaeger.grpc.port }}
        {{- end }}
        {{- if .Values.tempo.traces.zipkin.enabled }}
        - port: {{ .Values.tempo.traces.zipkin.port }}
        {{- end }}
        {{- if .Values.tempo.traces.otlp.http.enabled }}
        - port: {{ .Values.tempo.traces.otlp.http.port }}
        {{- if .Values.tempo.traces.otlp.http.enabledLegacy }}
        - port: 55681
        {{- end }}
        {{- end }}
        {{- if .Values.tempo.traces.otlp.grpc.enabled }}
        - port: {{ .Values.tempo.traces.otlp.grpc.port }}
        {{- if .Values.tempo.traces.otlp.grpc.enabledLegacy }}
        - port: 55680
        {{- end }}
        {{- end }}
        {{- if .Values.tempo.traces.opencensus.enabled }}
        - port: {{ .Values.tempo.traces.opencensus.port }}
        {{- end }}
      to:
        - podSelector:
            matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 14 }}
    {{- if .Values.vulture.enabled }}
    # Allow outbound connections to vulture
    - ports:
        - port: {{ .Values.vulture.containerPorts.http }}
      to:
        - podSelector:
            matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 14 }}
              app.kubernetes.io/component: vulture
    {{- end }}
    # Allow outbound connections to Memcached
    - ports:
      {{- if .Values.memcached.enabled }}
        - port: {{ .Values.memcached.containerPorts.memcached }}
      to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: memcached
              app.kubernetes.io/instance: {{ .Release.Name }}              
      {{- else }}
        - port: {{ .Values.externalMemcached.port }}
      {{- end }}
    {{- if .Values.ingester.networkPolicy.extraEgress }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.ingester.networkPolicy.extraEgress "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
  ingress:
    - ports:
        - port: {{ .Values.tempo.containerPorts.web }}
        - port: {{ .Values.tempo.containerPorts.gossipRing }}
        - port: {{ .Values.tempo.containerPorts.grpc }}
      {{- if not .Values.ingester.networkPolicy.allowExternal }}
      from:
        {{- if .Values.ingester.networkPolicy.addExternalClientAccess }}
        - podSelector:
            matchLabels:
              {{ template "grafana-tempo.ingester.fullname" . }}-ingester: "true"
        {{- end }}
        {{- if .Values.ingester.networkPolicy.ingressPodMatchLabels }}
        - podSelector:
            matchLabels: {{- include "common.tplvalues.render" (dict "value" .Values.ingester.networkPolicy.ingressPodMatchLabels "context" $ ) | nindent 14 }}
        {{- end }}
        {{- if .Values.ingester.networkPolicy.ingressNSMatchLabels }}
        - namespaceSelector:
            matchLabels: {{- include "common.tplvalues.render" (dict "value" .Values.ingester.networkPolicy.ingressNSMatchLabels "context" $ ) | nindent 14 }}
          {{- if .Values.ingester.networkPolicy.ingressNSPodMatchLabels }}
          podSelector:
            matchLabels: {{- include "common.tplvalues.render" (dict "value" .Values.ingester.networkPolicy.ingressNSPodMatchLabels "context" $ ) | nindent 14 }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- if .Values.ingester.networkPolicy.extraIngress }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.ingester.networkPolicy.extraIngress "context" $ ) | nindent 4 }}
    {{- end }}
{{- end }}
